updatee infrastructure side

diff --git a/infrastructure/templates/common.sh.tmpl b/infrastructure/templates/common.sh.tmpl
--- a/infrastructure/templates/common.sh.tmpl
+++ b/infrastructure/templates/common.sh.tmpl
@@ -177,6 +177,20 @@ setup_kubectl(){
 
   }
 
+setup_helm() {
+  if ! command -v helm &>/dev/null; then
+    echo "Helm not found, installing..."
+    curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg >/dev/null
+    sudo apt-get install apt-transport-https --yes
+    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
+    sudo apt-get update
+    sudo apt-get install -y helm
+  else
+    echo "Helm is already installed: $(command -v helm)"
+    helm version
+  fi
+}
+
 setup_dns(){
   # DNS setting 
   # env PUB_CTRL_IP="$PUB_CTRL_IP" envsubst < gke_dns_configmap.yml | kubectl apply -f -
